spring:
  application:
    name: springboot-app-final

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  
server:
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
  servlet:
    context-path: /v1
     
##### Dekorate HELM Stuff ###########
dekorate:
  kubernetes: 
    part-of: ^project.groupId^
   
  helm:
    name: springboot-app-final-chart
    #values:
    #-   property: metadata.namespace
        #paths: metadata.namespace
        #value: sasiperi
 
